wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.title, name="title"),
    path("new", views.new, name="new"),
    path("wiki/edit/<str:title>", views.edit, name="edit"),
    path("rand", views.rand, name="rand")
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
import random
from markdown2 import Markdown
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect


from . import util


def index(request):
    if request.method == "POST":
        entry = request.POST['get_entry']
        list = util.list_entries()
        res_list = []
        if entry in list:
            return HttpResponseRedirect(f"/wiki/{entry}")
        for i in list:
            if entry in i:
                res_list.append(i)
        lenght = len(res_list)
        if lenght > 0:
            return render(request, "encyclopedia/search_result.html", {
                "res_list": res_list,
                "entry": entry,
                "len": lenght,
                "list": list
            })
        else:
            return render(request, "encyclopedia/search_result.html", {
                "list": list,
                "entry": entry,
                 "len": lenght
            })
    else:
        return render(request, "encyclopedia/index.html", {
            "entries": util.list_entries(),
        })


def title(request, title):
    content = util.get_entry(title)
    if content == None:
        return render(request, "encyclopedia/error.html", {
            "title" : title
        })
    else:
        markdowner = Markdown()
        content = markdowner.convert(content)
        print(content)
        return render(request, "encyclopedia/entry.html", {
            "title": title,
            "content": content
        })


def new(request):
    if request.method == "POST":
        title = request.POST["new_title"]
        new_entry = request.POST["new_entry"]
        if title in util.list_entries():
            return HttpResponse("This entry already exists!")
        util.save_entry(title, new_entry)
        return HttpResponseRedirect(f"/wiki/{title}")
    else:
        return render(request, "encyclopedia/new.html")


def edit(request, title):
    if request.method == "POST":
        new_content = request.POST["edit_entry"]
        util.save_entry(title, new_content)
        return HttpResponseRedirect(f"/wiki/{title}")
    else:
        content = util.get_entry(title)
        if content == None:
            return render(request,"encyclopedia/error.html", {
                "title" : title
            })
        else:
            return render(request, "encyclopedia/edit.html", {
                "title": title,
                "content": content
            })


def rand(request):
    list = util.list_entries()
    n = random.randint(0, len(list)-1)
    return HttpResponseRedirect(f"/wiki/{list[n]}")

wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit
{% endblock %}

{% block body %}
    <h1>Edit entry " {{ title }} "</h1>
    
    <form method="post" id="edit_entry">
        {% csrf_token %}
        <textarea height="100px" id="textarea" form="edit_entry" name="edit_entry">{{ content }}</textarea><br>
        <input type="submit" value="Confirm Edit">
    </form>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <div id="entry_content">
        {{ content|safe }}
    </div>
    <div>
        <a href="/wiki/edit/{{title}}">
            <input type="submit" value="Edit">
        </a>
    </div>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Error
{% endblock %}

{% block body %}
    <h1>Error : entry "{{ title }}" not found...</h1>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <a href="/wiki/{{entry}}"><li>{{ entry }}</li></a>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:index' %}" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="get_entry" placeholder="Search">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:new' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:rand' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New
{% endblock %}

{% block body %}
    <h1>Create a new entry</h1>
    
    <form action="{% url 'encyclopedia:new' %}" method="post" id="new_entry">
        {% csrf_token %}
        <input class="new" type="text" name="new_title" placeholder="Entry Title"><br>
        <textarea height="100px" id="textarea" form="new_entry" name="new_entry" placeholder="Paste new entry here..."></textarea><br>
        <input type="submit" value="Create">
    </form>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/search_result.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Results
{% endblock %}

{% block body %}
    {% if len == 0 %}
    <h1>Entry "{{ entry }}" not found, hereunder all existing entries.</h1>
    <ul>
        {% for entry in list %}
            <a href="/wiki/{{entry}}"><li>{{ entry }}</li></a>
        {% endfor %}
    </ul>
    {% else %}
    <h1>Results for "{{ entry }}"</h1>
    <ul>
        {% for entry in res_list %}
            <a href="/wiki/{{entry}}"><li>{{ entry }}</li></a>
        {% endfor %}
    </ul>
    {% endif %}

{% endblock %}